# Generated by Django 5.1.5 on 2025-04-19 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('video_type', models.CharField(choices=[('lesson', 'Lesson'), ('conversation', 'Conversation'), ('music', 'Music'), ('vlog', 'Vlog'), ('movie_clip', 'Movie Clip'), ('news', 'News'), ('interview', 'Interview')], max_length=20)),
                ('duration', models.CharField(choices=[('short', 'Short (< 5 min)'), ('medium', 'Medium (5-15 min)'), ('long', 'Long (> 15 min)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
