# Generated by Django 5.1.5 on 2025-04-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learning_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='language_learning',
            field=models.CharField(blank=True, choices=[('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='practice_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_listening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_speaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_writing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_language',
            field=models.CharField(blank=True, choices=[('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
