# Generated by Django 5.1.5 on 2025-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_learning_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='native_language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
