# Generated by Django 5.2 on 2025-04-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture'),
        ('users', '0003_alter_profile_native_language'),
    ]

    operations = [
    ]
