# Generated by Django 5.1.5 on 2025-04-10 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_place_alter_goal_current_value_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 4, 13)),
        ),
    ]
