# Generated by Django 5.1.5 on 2025-04-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_goal_deadline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='place',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
