# Generated by Django 5.1.5 on 2025-04-11 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_favorite_unique_together_remove_favorite_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 4, 14)),
        ),
    ]
