# Generated by Django 5.2 on 2025-04-13 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 4, 16)),
        ),
    ]
