# Generated by Django 5.1.5 on 2025-04-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_goal_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_level', models.CharField(choices=[('casual', 'Casual (5-10 minutes)'), ('regular', 'Regular (15-20 minutes)'), ('dedicated', 'Dedicated (30+ minutes)'), ('intense', 'Intense (60+ minutes)')], max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner (A1)'), ('elementary', 'Elementary (A2)'), ('intermediate', 'Intermediate (B1)'), ('upper intermediate', 'Upper Intermediate (B2)'), ('advanced', 'Advanced (C1)'), ('proficient', 'Proficient (C2)')], max_length=20)),
                ('goals', models.CharField(blank=True, max_length=255)),
                ('areas', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
