# Generated by Django 5.1.5 on 2025-04-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_goal_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exercise_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_exercise_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
