# Generated by Django 5.1.5 on 2025-04-19 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_exercise_ready_profile_last_exercise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 4, 22)),
        ),
    ]
