# Generated by Django 5.1.5 on 2025-04-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_goal_affects_streak_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lessons_completed',
            new_name='exercises_completed',
        ),
    ]
