# Generated by Django 5.1.5 on 2025-04-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_lessons_completed_profile_exercises_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flashcards_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='videos_completed',
            field=models.IntegerField(default=0),
        ),
    ]
