# Generated by Django 5.1.5 on 2025-04-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_flashcards_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='practice_minutes',
        ),
    ]
