# Generated by Django 5.1.5 on 2025-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_profile_practice_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='langlocale_activities_completed',
            field=models.IntegerField(default=0),
        ),
    ]
