# Generated by Django 5.1.5 on 2025-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_goal_deadline_alter_profile_language_level'),
        ('users', '0022_profile_langlocale_activities_completed'),
    ]

    operations = [
    ]
