# Generated by Django 5.1.5 on 2025-04-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20250420_1515'),
        ('users', '0023_merge_20250420_1852'),
    ]

    operations = [
    ]
