# Generated by Django 5.1.5 on 2025-04-21 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20250420_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 4, 24)),
        ),
    ]
