# Generated by Django 5.2 on 2025-04-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_flashcard_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={},
        ),
    ]
