# Generated by Django 5.1.5 on 2025-04-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['num_revisions', 'updated_at']},
        ),
    ]
