# Generated by Django 5.1.5 on 2025-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='skill',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner (A1)'), ('elementary', 'Elementary (A2)'), ('intermediate', 'Intermediate (B1)'), ('upper_intermediate', 'Upper Intermediate (B2)'), ('advanced', 'Advanced (C1)'), ('proficient', 'Proficient (C2)')], max_length=250),
        ),
    ]
