# Generated by Django 5.1.5 on 2025-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='days_left',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='exercise',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
