# Generated by Django 5.1.5 on 2025-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_days_left_exercise_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='init',
            field=models.BooleanField(default=True),
        ),
    ]
