# Generated by Django 5.1.5 on 2025-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='new_deadline',
            field=models.DateField(default=None),
        ),
    ]
