# Generated by Django 5.1.5 on 2025-04-19 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercise_new_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='new_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
