# Generated by Django 5.1.5 on 2025-04-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_exercise_new_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='new_deadline',
        ),
    ]
