# Generated by Django 5.1.5 on 2025-04-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_remove_exercise_new_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
