# Generated by Django 5.1.5 on 2025-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_exercise_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='score',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
