# Generated by Django 5.1.5 on 2025-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_exercise_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
